// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// edge_c_cpp
double edge_c_cpp(double s, double h, double lower, double upper);
RcppExport SEXP _P3LS_edge_c_cpp(SEXP sSEXP, SEXP hSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_c_cpp(s, h, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// log_lambda_matrix_cpp
NumericMatrix log_lambda_matrix_cpp(List PPP_list, NumericVector T_seq, double h, double lower, double upper);
RcppExport SEXP _P3LS_log_lambda_matrix_cpp(SEXP PPP_listSEXP, SEXP T_seqSEXP, SEXP hSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type PPP_list(PPP_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T_seq(T_seqSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lambda_matrix_cpp(PPP_list, T_seq, h, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// inprod_mat_cpp
double inprod_mat_cpp(const arma::vec& u1, const arma::vec& u2, const arma::mat& K_hat, double lower, double upper);
RcppExport SEXP _P3LS_inprod_mat_cpp(SEXP u1SEXP, SEXP u2SEXP, SEXP K_hatSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u1(u1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u2(u2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K_hat(K_hatSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(inprod_mat_cpp(u1, u2, K_hat, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// gram_schmidt_cpp
arma::mat gram_schmidt_cpp(const arma::mat& U, const arma::mat& K_hat, double lower, double upper);
RcppExport SEXP _P3LS_gram_schmidt_cpp(SEXP USEXP, SEXP K_hatSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K_hat(K_hatSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(gram_schmidt_cpp(U, K_hat, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// bin_counts_matrix_cpp
NumericMatrix bin_counts_matrix_cpp(List PPP_list, NumericMatrix bins);
RcppExport SEXP _P3LS_bin_counts_matrix_cpp(SEXP PPP_listSEXP, SEXP binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type PPP_list(PPP_listSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bins(binsSEXP);
    rcpp_result_gen = Rcpp::wrap(bin_counts_matrix_cpp(PPP_list, bins));
    return rcpp_result_gen;
END_RCPP
}
// cov_estimator_core_cpp
List cov_estimator_core_cpp(List PROCESS, NumericVector grids, double bwd);
RcppExport SEXP _P3LS_cov_estimator_core_cpp(SEXP PROCESSSEXP, SEXP gridsSEXP, SEXP bwdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type PROCESS(PROCESSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grids(gridsSEXP);
    Rcpp::traits::input_parameter< double >::type bwd(bwdSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_estimator_core_cpp(PROCESS, grids, bwd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_P3LS_edge_c_cpp", (DL_FUNC) &_P3LS_edge_c_cpp, 4},
    {"_P3LS_log_lambda_matrix_cpp", (DL_FUNC) &_P3LS_log_lambda_matrix_cpp, 5},
    {"_P3LS_inprod_mat_cpp", (DL_FUNC) &_P3LS_inprod_mat_cpp, 5},
    {"_P3LS_gram_schmidt_cpp", (DL_FUNC) &_P3LS_gram_schmidt_cpp, 4},
    {"_P3LS_bin_counts_matrix_cpp", (DL_FUNC) &_P3LS_bin_counts_matrix_cpp, 2},
    {"_P3LS_cov_estimator_core_cpp", (DL_FUNC) &_P3LS_cov_estimator_core_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_P3LS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
