# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edge_c_cpp <- function(s, h, lower, upper) {
    .Call(`_P3LS_edge_c_cpp`, s, h, lower, upper)
}

log_lambda_matrix_cpp <- function(PPP_list, T_seq, h, lower, upper) {
    .Call(`_P3LS_log_lambda_matrix_cpp`, PPP_list, T_seq, h, lower, upper)
}

inprod_mat_cpp <- function(u1, u2, K_hat, lower, upper) {
    .Call(`_P3LS_inprod_mat_cpp`, u1, u2, K_hat, lower, upper)
}

gram_schmidt_cpp <- function(U, K_hat, lower, upper) {
    .Call(`_P3LS_gram_schmidt_cpp`, U, K_hat, lower, upper)
}

bin_counts_matrix_cpp <- function(PPP_list, bins) {
    .Call(`_P3LS_bin_counts_matrix_cpp`, PPP_list, bins)
}

cov_estimator_core_cpp <- function(PROCESS, grids, bwd) {
    .Call(`_P3LS_cov_estimator_core_cpp`, PROCESS, grids, bwd)
}

